/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_p = new javax.swing.JPanel();
        south_p = new javax.swing.JPanel();
        center_p = new javax.swing.JPanel();
        centerWest_p = new javax.swing.JPanel();
        bt_home = new javax.swing.JButton();
        bt_adminEmp = new javax.swing.JButton();
        bt_adminAtt = new javax.swing.JButton();
        bt_adminVac = new javax.swing.JButton();
        bt_userMode = new javax.swing.JButton();
        centerCard_p = new javax.swing.JPanel();
        admin_p = new javax.swing.JPanel();
        homeImage_l = new javax.swing.JLabel();
        adminEmp_p = new javax.swing.JPanel();
        adminEmp_north_p = new javax.swing.JPanel();
        bt_dsearch = new javax.swing.JButton();
        bt_addEmp = new javax.swing.JButton();
        jsp_empTable = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        adminAtt_p = new javax.swing.JPanel();
        adminAtt_north_p = new javax.swing.JPanel();
        year_cb = new javax.swing.JComboBox<>();
        year_l = new javax.swing.JLabel();
        month_cb = new javax.swing.JComboBox<>();
        month_l = new javax.swing.JLabel();
        day_cb = new javax.swing.JComboBox<>();
        day_l = new javax.swing.JLabel();
        bt_find = new javax.swing.JButton();
        jsp_attTable = new javax.swing.JScrollPane();
        attTable = new javax.swing.JTable();
        adminVac_p = new javax.swing.JPanel();
        adminVac_north_p = new javax.swing.JPanel();
        bt_cfirmDenyList = new javax.swing.JButton();
        jsp_vacTable = new javax.swing.JScrollPane();
        vacTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("관리자 모드");

        north_p.setPreferredSize(new java.awt.Dimension(965, 50));

        javax.swing.GroupLayout north_pLayout = new javax.swing.GroupLayout(north_p);
        north_p.setLayout(north_pLayout);
        north_pLayout.setHorizontalGroup(
            north_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        north_pLayout.setVerticalGroup(
            north_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(north_p, java.awt.BorderLayout.PAGE_START);

        south_p.setPreferredSize(new java.awt.Dimension(965, 50));

        javax.swing.GroupLayout south_pLayout = new javax.swing.GroupLayout(south_p);
        south_p.setLayout(south_pLayout);
        south_pLayout.setHorizontalGroup(
            south_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        south_pLayout.setVerticalGroup(
            south_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(south_p, java.awt.BorderLayout.PAGE_END);

        center_p.setLayout(new java.awt.BorderLayout());

        centerWest_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        centerWest_p.setPreferredSize(new java.awt.Dimension(240, 480));
        centerWest_p.setLayout(new java.awt.GridLayout(5, 1, 0, 40));

        bt_home.setText("홈");
        centerWest_p.add(bt_home);

        bt_adminEmp.setText("사원 관리");
        centerWest_p.add(bt_adminEmp);

        bt_adminAtt.setText("근태 관리");
        centerWest_p.add(bt_adminAtt);

        bt_adminVac.setText("휴가 관리");
        centerWest_p.add(bt_adminVac);

        bt_userMode.setText("사용자 모드");
        centerWest_p.add(bt_userMode);

        center_p.add(centerWest_p, java.awt.BorderLayout.LINE_START);

        centerCard_p.setLayout(new java.awt.CardLayout());

        admin_p.setLayout(new java.awt.BorderLayout());

        homeImage_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_p.add(homeImage_l, java.awt.BorderLayout.CENTER);

        centerCard_p.add(admin_p, "adminCard");

        adminEmp_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        adminEmp_p.setLayout(new java.awt.BorderLayout());

        adminEmp_north_p.setPreferredSize(new java.awt.Dimension(725, 60));
        adminEmp_north_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 15));

        bt_dsearch.setText("상세 조회");
        adminEmp_north_p.add(bt_dsearch);

        bt_addEmp.setText("사원 추가");
        adminEmp_north_p.add(bt_addEmp);

        adminEmp_p.add(adminEmp_north_p, java.awt.BorderLayout.PAGE_START);

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "사원 번호", "사원 이름", "직급", "부서", "급여", "입사일", "재직 상태", "관리자"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp_empTable.setViewportView(empTable);

        adminEmp_p.add(jsp_empTable, java.awt.BorderLayout.CENTER);

        centerCard_p.add(adminEmp_p, "adminEmpCard");

        adminAtt_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        adminAtt_p.setLayout(new java.awt.BorderLayout());

        adminAtt_north_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15));

        year_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adminAtt_north_p.add(year_cb);

        year_l.setText("년");
        adminAtt_north_p.add(year_l);

        month_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        adminAtt_north_p.add(month_cb);

        month_l.setText("월");
        adminAtt_north_p.add(month_l);

        day_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        adminAtt_north_p.add(day_cb);

        day_l.setText("일");
        adminAtt_north_p.add(day_l);

        bt_find.setText("조회");
        adminAtt_north_p.add(bt_find);

        adminAtt_p.add(adminAtt_north_p, java.awt.BorderLayout.PAGE_START);

        attTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "사원 번호", "사원 이름", "날짜", "출근 시간", "퇴근 시간", "근태"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp_attTable.setViewportView(attTable);

        adminAtt_p.add(jsp_attTable, java.awt.BorderLayout.CENTER);

        centerCard_p.add(adminAtt_p, "adminAttCard");

        adminVac_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        adminVac_p.setLayout(new java.awt.BorderLayout());

        adminVac_north_p.setPreferredSize(new java.awt.Dimension(725, 40));
        adminVac_north_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        bt_cfirmDenyList.setText("승인 / 반려 내역");
        adminVac_north_p.add(bt_cfirmDenyList);

        adminVac_p.add(adminVac_north_p, java.awt.BorderLayout.PAGE_START);

        vacTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "사원 번호", "사원 이름", "부서", "휴가 종류", "휴가 시작일", "휴가 기간", "남은 휴가", "결재 상태", "결재 날짜"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp_vacTable.setViewportView(vacTable);

        adminVac_p.add(jsp_vacTable, java.awt.BorderLayout.CENTER);

        centerCard_p.add(adminVac_p, "adminVacCard");

        center_p.add(centerCard_p, java.awt.BorderLayout.CENTER);

        getContentPane().add(center_p, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminAtt_north_p;
    private javax.swing.JPanel adminAtt_p;
    private javax.swing.JPanel adminEmp_north_p;
    private javax.swing.JPanel adminEmp_p;
    private javax.swing.JPanel adminVac_north_p;
    private javax.swing.JPanel adminVac_p;
    private javax.swing.JPanel admin_p;
    private javax.swing.JTable attTable;
    private javax.swing.JButton bt_addEmp;
    private javax.swing.JButton bt_adminAtt;
    private javax.swing.JButton bt_adminEmp;
    private javax.swing.JButton bt_adminVac;
    private javax.swing.JButton bt_cfirmDenyList;
    private javax.swing.JButton bt_dsearch;
    private javax.swing.JButton bt_find;
    private javax.swing.JButton bt_home;
    private javax.swing.JButton bt_userMode;
    private javax.swing.JPanel centerCard_p;
    private javax.swing.JPanel centerWest_p;
    private javax.swing.JPanel center_p;
    private javax.swing.JComboBox<String> day_cb;
    private javax.swing.JLabel day_l;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel homeImage_l;
    private javax.swing.JScrollPane jsp_attTable;
    private javax.swing.JScrollPane jsp_empTable;
    private javax.swing.JScrollPane jsp_vacTable;
    private javax.swing.JComboBox<String> month_cb;
    private javax.swing.JLabel month_l;
    private javax.swing.JPanel north_p;
    private javax.swing.JPanel south_p;
    private javax.swing.JTable vacTable;
    private javax.swing.JComboBox<String> year_cb;
    private javax.swing.JLabel year_l;
    // End of variables declaration//GEN-END:variables
}
