/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class EditMyinfoForm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditMyinfoForm.class.getName());

    /**
     * Creates new form EditMyinfoForm
     */
    public EditMyinfoForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        south_p = new javax.swing.JPanel();
        bt_edit = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        center_p = new javax.swing.JPanel();
        empno_p = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ename_p = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        pos_p = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        dept_p = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        sal_p = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        hiredate_p = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        email_p = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        phone_p = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        att_p = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        mgr_p = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("내 정보 수정");

        south_p.setPreferredSize(new java.awt.Dimension(355, 50));
        south_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 12));

        bt_edit.setText("수정");
        south_p.add(bt_edit);

        bt_cancel.setText("취소");
        south_p.add(bt_cancel);

        getContentPane().add(south_p, java.awt.BorderLayout.PAGE_END);

        center_p.setLayout(new java.awt.GridLayout(10, 1));

        empno_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        empno_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel1.setText("사원 번호 :");
        empno_p.add(jLabel1);

        jTextField1.setColumns(8);
        empno_p.add(jTextField1);

        center_p.add(empno_p);

        ename_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        ename_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel11.setText("사원 이름 :");
        ename_p.add(jLabel11);

        jTextField11.setColumns(8);
        ename_p.add(jTextField11);

        center_p.add(ename_p);

        pos_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pos_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel12.setText("직급 :");
        pos_p.add(jLabel12);

        jTextField12.setColumns(8);
        pos_p.add(jTextField12);

        center_p.add(pos_p);

        dept_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        dept_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel13.setText("부서 :");
        dept_p.add(jLabel13);

        jTextField13.setColumns(8);
        dept_p.add(jTextField13);

        center_p.add(dept_p);

        sal_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        sal_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel14.setText("급여 :");
        sal_p.add(jLabel14);

        jTextField14.setColumns(8);
        sal_p.add(jTextField14);

        center_p.add(sal_p);

        hiredate_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        hiredate_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel15.setText("입사일 :");
        hiredate_p.add(jLabel15);

        jTextField15.setColumns(8);
        hiredate_p.add(jTextField15);

        center_p.add(hiredate_p);

        email_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        email_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel16.setText("이메일 :");
        email_p.add(jLabel16);

        jTextField16.setColumns(18);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        email_p.add(jTextField16);

        center_p.add(email_p);

        phone_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        phone_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel17.setText("연락처 :");
        phone_p.add(jLabel17);

        jTextField17.setColumns(8);
        phone_p.add(jTextField17);

        center_p.add(phone_p);

        att_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        att_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel18.setText("재직 상태 :");
        att_p.add(jLabel18);

        jTextField18.setColumns(8);
        att_p.add(jTextField18);

        center_p.add(att_p);

        mgr_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        mgr_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 12));

        jLabel19.setText("관리자 번호 :");
        mgr_p.add(jLabel19);

        jTextField19.setColumns(8);
        mgr_p.add(jTextField19);

        center_p.add(mgr_p);

        getContentPane().add(center_p, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditMyinfoForm dialog = new EditMyinfoForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel att_p;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_edit;
    private javax.swing.JPanel center_p;
    private javax.swing.JPanel dept_p;
    private javax.swing.JPanel email_p;
    private javax.swing.JPanel empno_p;
    private javax.swing.JPanel ename_p;
    private javax.swing.JPanel hiredate_p;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JPanel mgr_p;
    private javax.swing.JPanel phone_p;
    private javax.swing.JPanel pos_p;
    private javax.swing.JPanel sal_p;
    private javax.swing.JPanel south_p;
    // End of variables declaration//GEN-END:variables
}
