/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form empFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        south_p = new javax.swing.JPanel();
        bt_login = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        north_p = new javax.swing.JPanel();
        center_p = new javax.swing.JPanel();
        id_l = new javax.swing.JLabel();
        id_tf = new javax.swing.JTextField();
        pw_l = new javax.swing.JLabel();
        pw_pf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("사원 관리 프로그램");

        south_p.setPreferredSize(new java.awt.Dimension(350, 50));
        south_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 30, 15));

        bt_login.setText("로그인");
        south_p.add(bt_login);

        bt_cancel.setText("취소");
        south_p.add(bt_cancel);

        getContentPane().add(south_p, java.awt.BorderLayout.PAGE_END);

        north_p.setPreferredSize(new java.awt.Dimension(350, 30));

        javax.swing.GroupLayout north_pLayout = new javax.swing.GroupLayout(north_p);
        north_p.setLayout(north_pLayout);
        north_pLayout.setHorizontalGroup(
            north_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        north_pLayout.setVerticalGroup(
            north_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(north_p, java.awt.BorderLayout.PAGE_START);

        center_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        center_p.setLayout(new java.awt.GridLayout(2, 1));

        id_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_l.setText("아이디");
        center_p.add(id_l);
        center_p.add(id_tf);

        pw_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pw_l.setText("비밀번호");
        center_p.add(pw_l);
        center_p.add(pw_pf);

        getContentPane().add(center_p, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_login;
    private javax.swing.JPanel center_p;
    private javax.swing.JLabel id_l;
    private javax.swing.JTextField id_tf;
    private javax.swing.JPanel north_p;
    private javax.swing.JLabel pw_l;
    private javax.swing.JPasswordField pw_pf;
    private javax.swing.JPanel south_p;
    // End of variables declaration//GEN-END:variables
}
