/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import vo.EmpVO;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author zhfja
 */
public class WorkInOut extends JFrame {

    // 변수 선언
    private JButton bt_in;
    private JButton bt_out;
    private JLabel inOutImage_l;
    private JPanel north_p;
    private String user_name;
    // 변수 선언 끝
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkInOut.class.getName());

    /**
     * Creates new form WorkInOut
     */
    //기본 생성자
    public WorkInOut() {
        initComponents();
        EmpVO emp = new EmpVO();
        user_name = emp.getEname();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //출근 버튼 이벤트
        bt_in.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String message;
                System.out.println(user_name);
                if (user_name != null && !user_name.isEmpty()) {

                    message = user_name + "님 출근하셨습니다. 오늘도 열심히 힘내세요.";

                } else {

                    message = "출근했습니다. 오늘도 열심히 힘내세요."; // 이름 정보가 없을 경우 기본 메시지

                }

                JOptionPane.showMessageDialog(WorkInOut.this,

                        message, "출근 알림", JOptionPane.INFORMATION_MESSAGE);

            }
        });
        // 퇴근 버튼 이벤트
        bt_out.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(WorkInOut.this,
                        "퇴근했습니다 오늘 하루 지옥같이 고생했습니다.", "퇴근 알림", JOptionPane.INFORMATION_MESSAGE);
            }

        });



    }//기본 생성자의 끝


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_p = new JPanel();
        bt_in = new JButton();
        bt_out = new JButton();
        inOutImage_l = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("출 / 퇴근");

        north_p.setPreferredSize(new java.awt.Dimension(364, 150));
        north_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        bt_in.setText("출근");
        north_p.add(bt_in);

        bt_out.setText("퇴근");
        north_p.add(bt_out);

        getContentPane().add(north_p, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(inOutImage_l, java.awt.BorderLayout.CENTER);

        pack();
        this.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WorkInOut().setVisible(true));
    }

}
